version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: >
      sh -c "yarn install && yarn run dev & yarn run storybook"
    ports:
      - "80:80"
      - "6006:6006"
